resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/enel1221/zarf-operator
  newTag: v0.1.0
- name: zarf-sidecar
  newName: ghcr.io/enel1221/zarf-operator-sidecar
  newTag: v0.1.0
