// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: zarf/v1/zarf.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Source                  string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Components              []string               `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	SetVariables            map[string]string      `protobuf:"bytes,3,rep,name=set_variables,json=setVariables,proto3" json:"set_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AdoptExistingResources  bool                   `protobuf:"varint,4,opt,name=adopt_existing_resources,json=adoptExistingResources,proto3" json:"adopt_existing_resources,omitempty"`
	Timeout                 *durationpb.Duration   `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Retries                 int32                  `protobuf:"varint,6,opt,name=retries,proto3" json:"retries,omitempty"`
	NamespaceOverride       string                 `protobuf:"bytes,7,opt,name=namespace_override,json=namespaceOverride,proto3" json:"namespace_override,omitempty"`
	Shasum                  string                 `protobuf:"bytes,8,opt,name=shasum,proto3" json:"shasum,omitempty"`
	SkipSignatureValidation bool                   `protobuf:"varint,9,opt,name=skip_signature_validation,json=skipSignatureValidation,proto3" json:"skip_signature_validation,omitempty"`
	Architecture            string                 `protobuf:"bytes,10,opt,name=architecture,proto3" json:"architecture,omitempty"`
	OciConcurrency          int32                  `protobuf:"varint,11,opt,name=oci_concurrency,json=ociConcurrency,proto3" json:"oci_concurrency,omitempty"`
	PublicKeyPath           string                 `protobuf:"bytes,12,opt,name=public_key_path,json=publicKeyPath,proto3" json:"public_key_path,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{0}
}

func (x *DeployRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DeployRequest) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *DeployRequest) GetSetVariables() map[string]string {
	if x != nil {
		return x.SetVariables
	}
	return nil
}

func (x *DeployRequest) GetAdoptExistingResources() bool {
	if x != nil {
		return x.AdoptExistingResources
	}
	return false
}

func (x *DeployRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *DeployRequest) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *DeployRequest) GetNamespaceOverride() string {
	if x != nil {
		return x.NamespaceOverride
	}
	return ""
}

func (x *DeployRequest) GetShasum() string {
	if x != nil {
		return x.Shasum
	}
	return ""
}

func (x *DeployRequest) GetSkipSignatureValidation() bool {
	if x != nil {
		return x.SkipSignatureValidation
	}
	return false
}

func (x *DeployRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *DeployRequest) GetOciConcurrency() int32 {
	if x != nil {
		return x.OciConcurrency
	}
	return 0
}

func (x *DeployRequest) GetPublicKeyPath() string {
	if x != nil {
		return x.PublicKeyPath
	}
	return ""
}

type DeployResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PackageName        string                 `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Version            string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Generation         int32                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	DeployedComponents []*DeployedComponent   `protobuf:"bytes,4,rep,name=deployed_components,json=deployedComponents,proto3" json:"deployed_components,omitempty"`
	Error              string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{1}
}

func (x *DeployResponse) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *DeployResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeployResponse) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *DeployResponse) GetDeployedComponents() []*DeployedComponent {
	if x != nil {
		return x.DeployedComponents
	}
	return nil
}

func (x *DeployResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeployedComponent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	InstalledCharts    []*InstalledChart      `protobuf:"bytes,3,rep,name=installed_charts,json=installedCharts,proto3" json:"installed_charts,omitempty"`
	ObservedGeneration int32                  `protobuf:"varint,4,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeployedComponent) Reset() {
	*x = DeployedComponent{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployedComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployedComponent) ProtoMessage() {}

func (x *DeployedComponent) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployedComponent.ProtoReflect.Descriptor instead.
func (*DeployedComponent) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{2}
}

func (x *DeployedComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployedComponent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeployedComponent) GetInstalledCharts() []*InstalledChart {
	if x != nil {
		return x.InstalledCharts
	}
	return nil
}

func (x *DeployedComponent) GetObservedGeneration() int32 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

type InstalledChart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ChartName     string                 `protobuf:"bytes,2,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledChart) Reset() {
	*x = InstalledChart{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledChart) ProtoMessage() {}

func (x *InstalledChart) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledChart.ProtoReflect.Descriptor instead.
func (*InstalledChart) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{3}
}

func (x *InstalledChart) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InstalledChart) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *InstalledChart) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Components    []string               `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *RemoveRequest) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDeployedPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeployedPackageRequest) Reset() {
	*x = GetDeployedPackageRequest{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeployedPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeployedPackageRequest) ProtoMessage() {}

func (x *GetDeployedPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeployedPackageRequest.ProtoReflect.Descriptor instead.
func (*GetDeployedPackageRequest) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{6}
}

func (x *GetDeployedPackageRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

type GetDeployedPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       *PackageInfo           `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeployedPackageResponse) Reset() {
	*x = GetDeployedPackageResponse{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeployedPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeployedPackageResponse) ProtoMessage() {}

func (x *GetDeployedPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeployedPackageResponse.ProtoReflect.Descriptor instead.
func (*GetDeployedPackageResponse) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeployedPackageResponse) GetPackage() *PackageInfo {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *GetDeployedPackageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListDeployedPackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeployedPackagesRequest) Reset() {
	*x = ListDeployedPackagesRequest{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeployedPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeployedPackagesRequest) ProtoMessage() {}

func (x *ListDeployedPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeployedPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListDeployedPackagesRequest) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{8}
}

type ListDeployedPackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*PackageInfo         `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeployedPackagesResponse) Reset() {
	*x = ListDeployedPackagesResponse{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeployedPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeployedPackagesResponse) ProtoMessage() {}

func (x *ListDeployedPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeployedPackagesResponse.ProtoReflect.Descriptor instead.
func (*ListDeployedPackagesResponse) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{9}
}

func (x *ListDeployedPackagesResponse) GetPackages() []*PackageInfo {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *ListDeployedPackagesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PackageInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version            string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Generation         int32                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	CliVersion         string                 `protobuf:"bytes,4,opt,name=cli_version,json=cliVersion,proto3" json:"cli_version,omitempty"`
	DeployedComponents []*DeployedComponent   `protobuf:"bytes,5,rep,name=deployed_components,json=deployedComponents,proto3" json:"deployed_components,omitempty"`
	NamespaceOverride  string                 `protobuf:"bytes,6,opt,name=namespace_override,json=namespaceOverride,proto3" json:"namespace_override,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{10}
}

func (x *PackageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageInfo) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *PackageInfo) GetCliVersion() string {
	if x != nil {
		return x.CliVersion
	}
	return ""
}

func (x *PackageInfo) GetDeployedComponents() []*DeployedComponent {
	if x != nil {
		return x.DeployedComponents
	}
	return nil
}

func (x *PackageInfo) GetNamespaceOverride() string {
	if x != nil {
		return x.NamespaceOverride
	}
	return ""
}

type GetPackageMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageMetadataRequest) Reset() {
	*x = GetPackageMetadataRequest{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageMetadataRequest) ProtoMessage() {}

func (x *GetPackageMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetPackageMetadataRequest) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{11}
}

func (x *GetPackageMetadataRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetPackageMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *PackageMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageMetadataResponse) Reset() {
	*x = GetPackageMetadataResponse{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageMetadataResponse) ProtoMessage() {}

func (x *GetPackageMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetPackageMetadataResponse) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{12}
}

func (x *GetPackageMetadataResponse) GetMetadata() *PackageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetPackageMetadataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PackageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Components    []string               `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty"`
	Architecture  string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageMetadata) Reset() {
	*x = PackageMetadata{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageMetadata) ProtoMessage() {}

func (x *PackageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageMetadata.ProtoReflect.Descriptor instead.
func (*PackageMetadata) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{13}
}

func (x *PackageMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PackageMetadata) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *PackageMetadata) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{14}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_zarf_v1_zarf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zarf_v1_zarf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_zarf_v1_zarf_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_zarf_v1_zarf_proto protoreflect.FileDescriptor

const file_zarf_v1_zarf_proto_rawDesc = "" +
	"\n" +
	"\x12zarf/v1/zarf.proto\x12\azarf.v1\x1a\x1egoogle/protobuf/duration.proto\"\xd8\x04\n" +
	"\rDeployRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"components\x18\x02 \x03(\tR\n" +
	"components\x12M\n" +
	"\rset_variables\x18\x03 \x03(\v2(.zarf.v1.DeployRequest.SetVariablesEntryR\fsetVariables\x128\n" +
	"\x18adopt_existing_resources\x18\x04 \x01(\bR\x16adoptExistingResources\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x18\n" +
	"\aretries\x18\x06 \x01(\x05R\aretries\x12-\n" +
	"\x12namespace_override\x18\a \x01(\tR\x11namespaceOverride\x12\x16\n" +
	"\x06shasum\x18\b \x01(\tR\x06shasum\x12:\n" +
	"\x19skip_signature_validation\x18\t \x01(\bR\x17skipSignatureValidation\x12\"\n" +
	"\farchitecture\x18\n" +
	" \x01(\tR\farchitecture\x12'\n" +
	"\x0foci_concurrency\x18\v \x01(\x05R\x0eociConcurrency\x12&\n" +
	"\x0fpublic_key_path\x18\f \x01(\tR\rpublicKeyPath\x1a?\n" +
	"\x11SetVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x0eDeployResponse\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x05R\n" +
	"generation\x12K\n" +
	"\x13deployed_components\x18\x04 \x03(\v2\x1a.zarf.v1.DeployedComponentR\x12deployedComponents\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xb4\x01\n" +
	"\x11DeployedComponent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12B\n" +
	"\x10installed_charts\x18\x03 \x03(\v2\x17.zarf.v1.InstalledChartR\x0finstalledCharts\x12/\n" +
	"\x13observed_generation\x18\x04 \x01(\x05R\x12observedGeneration\"e\n" +
	"\x0eInstalledChart\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"chart_name\x18\x02 \x01(\tR\tchartName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"R\n" +
	"\rRemoveRequest\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12\x1e\n" +
	"\n" +
	"components\x18\x02 \x03(\tR\n" +
	"components\"&\n" +
	"\x0eRemoveResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\">\n" +
	"\x19GetDeployedPackageRequest\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\"b\n" +
	"\x1aGetDeployedPackageResponse\x12.\n" +
	"\apackage\x18\x01 \x01(\v2\x14.zarf.v1.PackageInfoR\apackage\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1d\n" +
	"\x1bListDeployedPackagesRequest\"f\n" +
	"\x1cListDeployedPackagesResponse\x120\n" +
	"\bpackages\x18\x01 \x03(\v2\x14.zarf.v1.PackageInfoR\bpackages\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf8\x01\n" +
	"\vPackageInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x05R\n" +
	"generation\x12\x1f\n" +
	"\vcli_version\x18\x04 \x01(\tR\n" +
	"cliVersion\x12K\n" +
	"\x13deployed_components\x18\x05 \x03(\v2\x1a.zarf.v1.DeployedComponentR\x12deployedComponents\x12-\n" +
	"\x12namespace_override\x18\x06 \x01(\tR\x11namespaceOverride\"3\n" +
	"\x19GetPackageMetadataRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\"h\n" +
	"\x1aGetPackageMetadataResponse\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.zarf.v1.PackageMetadataR\bmetadata\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa5\x01\n" +
	"\x0fPackageMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"components\x18\x04 \x03(\tR\n" +
	"components\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xe1\x03\n" +
	"\vZarfService\x129\n" +
	"\x06Deploy\x12\x16.zarf.v1.DeployRequest\x1a\x17.zarf.v1.DeployResponse\x129\n" +
	"\x06Remove\x12\x16.zarf.v1.RemoveRequest\x1a\x17.zarf.v1.RemoveResponse\x12]\n" +
	"\x12GetDeployedPackage\x12\".zarf.v1.GetDeployedPackageRequest\x1a#.zarf.v1.GetDeployedPackageResponse\x12c\n" +
	"\x14ListDeployedPackages\x12$.zarf.v1.ListDeployedPackagesRequest\x1a%.zarf.v1.ListDeployedPackagesResponse\x12]\n" +
	"\x12GetPackageMetadata\x12\".zarf.v1.GetPackageMetadataRequest\x1a#.zarf.v1.GetPackageMetadataResponse\x129\n" +
	"\x06Health\x12\x16.zarf.v1.HealthRequest\x1a\x17.zarf.v1.HealthResponseB/Z-github.com/enel1221/zarf-operator/pkg/zarf/v1b\x06proto3"

var (
	file_zarf_v1_zarf_proto_rawDescOnce sync.Once
	file_zarf_v1_zarf_proto_rawDescData []byte
)

func file_zarf_v1_zarf_proto_rawDescGZIP() []byte {
	file_zarf_v1_zarf_proto_rawDescOnce.Do(func() {
		file_zarf_v1_zarf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zarf_v1_zarf_proto_rawDesc), len(file_zarf_v1_zarf_proto_rawDesc)))
	})
	return file_zarf_v1_zarf_proto_rawDescData
}

var file_zarf_v1_zarf_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_zarf_v1_zarf_proto_goTypes = []any{
	(*DeployRequest)(nil),                // 0: zarf.v1.DeployRequest
	(*DeployResponse)(nil),               // 1: zarf.v1.DeployResponse
	(*DeployedComponent)(nil),            // 2: zarf.v1.DeployedComponent
	(*InstalledChart)(nil),               // 3: zarf.v1.InstalledChart
	(*RemoveRequest)(nil),                // 4: zarf.v1.RemoveRequest
	(*RemoveResponse)(nil),               // 5: zarf.v1.RemoveResponse
	(*GetDeployedPackageRequest)(nil),    // 6: zarf.v1.GetDeployedPackageRequest
	(*GetDeployedPackageResponse)(nil),   // 7: zarf.v1.GetDeployedPackageResponse
	(*ListDeployedPackagesRequest)(nil),  // 8: zarf.v1.ListDeployedPackagesRequest
	(*ListDeployedPackagesResponse)(nil), // 9: zarf.v1.ListDeployedPackagesResponse
	(*PackageInfo)(nil),                  // 10: zarf.v1.PackageInfo
	(*GetPackageMetadataRequest)(nil),    // 11: zarf.v1.GetPackageMetadataRequest
	(*GetPackageMetadataResponse)(nil),   // 12: zarf.v1.GetPackageMetadataResponse
	(*PackageMetadata)(nil),              // 13: zarf.v1.PackageMetadata
	(*HealthRequest)(nil),                // 14: zarf.v1.HealthRequest
	(*HealthResponse)(nil),               // 15: zarf.v1.HealthResponse
	nil,                                  // 16: zarf.v1.DeployRequest.SetVariablesEntry
	(*durationpb.Duration)(nil),          // 17: google.protobuf.Duration
}
var file_zarf_v1_zarf_proto_depIdxs = []int32{
	16, // 0: zarf.v1.DeployRequest.set_variables:type_name -> zarf.v1.DeployRequest.SetVariablesEntry
	17, // 1: zarf.v1.DeployRequest.timeout:type_name -> google.protobuf.Duration
	2,  // 2: zarf.v1.DeployResponse.deployed_components:type_name -> zarf.v1.DeployedComponent
	3,  // 3: zarf.v1.DeployedComponent.installed_charts:type_name -> zarf.v1.InstalledChart
	10, // 4: zarf.v1.GetDeployedPackageResponse.package:type_name -> zarf.v1.PackageInfo
	10, // 5: zarf.v1.ListDeployedPackagesResponse.packages:type_name -> zarf.v1.PackageInfo
	2,  // 6: zarf.v1.PackageInfo.deployed_components:type_name -> zarf.v1.DeployedComponent
	13, // 7: zarf.v1.GetPackageMetadataResponse.metadata:type_name -> zarf.v1.PackageMetadata
	0,  // 8: zarf.v1.ZarfService.Deploy:input_type -> zarf.v1.DeployRequest
	4,  // 9: zarf.v1.ZarfService.Remove:input_type -> zarf.v1.RemoveRequest
	6,  // 10: zarf.v1.ZarfService.GetDeployedPackage:input_type -> zarf.v1.GetDeployedPackageRequest
	8,  // 11: zarf.v1.ZarfService.ListDeployedPackages:input_type -> zarf.v1.ListDeployedPackagesRequest
	11, // 12: zarf.v1.ZarfService.GetPackageMetadata:input_type -> zarf.v1.GetPackageMetadataRequest
	14, // 13: zarf.v1.ZarfService.Health:input_type -> zarf.v1.HealthRequest
	1,  // 14: zarf.v1.ZarfService.Deploy:output_type -> zarf.v1.DeployResponse
	5,  // 15: zarf.v1.ZarfService.Remove:output_type -> zarf.v1.RemoveResponse
	7,  // 16: zarf.v1.ZarfService.GetDeployedPackage:output_type -> zarf.v1.GetDeployedPackageResponse
	9,  // 17: zarf.v1.ZarfService.ListDeployedPackages:output_type -> zarf.v1.ListDeployedPackagesResponse
	12, // 18: zarf.v1.ZarfService.GetPackageMetadata:output_type -> zarf.v1.GetPackageMetadataResponse
	15, // 19: zarf.v1.ZarfService.Health:output_type -> zarf.v1.HealthResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_zarf_v1_zarf_proto_init() }
func file_zarf_v1_zarf_proto_init() {
	if File_zarf_v1_zarf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zarf_v1_zarf_proto_rawDesc), len(file_zarf_v1_zarf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zarf_v1_zarf_proto_goTypes,
		DependencyIndexes: file_zarf_v1_zarf_proto_depIdxs,
		MessageInfos:      file_zarf_v1_zarf_proto_msgTypes,
	}.Build()
	File_zarf_v1_zarf_proto = out.File
	file_zarf_v1_zarf_proto_goTypes = nil
	file_zarf_v1_zarf_proto_depIdxs = nil
}
