// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: zarf/v1/zarf.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZarfService_Deploy_FullMethodName               = "/zarf.v1.ZarfService/Deploy"
	ZarfService_Remove_FullMethodName               = "/zarf.v1.ZarfService/Remove"
	ZarfService_GetDeployedPackage_FullMethodName   = "/zarf.v1.ZarfService/GetDeployedPackage"
	ZarfService_ListDeployedPackages_FullMethodName = "/zarf.v1.ZarfService/ListDeployedPackages"
	ZarfService_GetPackageMetadata_FullMethodName   = "/zarf.v1.ZarfService/GetPackageMetadata"
	ZarfService_Health_FullMethodName               = "/zarf.v1.ZarfService/Health"
)

// ZarfServiceClient is the client API for ZarfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZarfServiceClient interface {
	// Deploy deploys a Zarf package
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
	// Remove removes a deployed package
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	// GetDeployedPackage gets info about a deployed package
	GetDeployedPackage(ctx context.Context, in *GetDeployedPackageRequest, opts ...grpc.CallOption) (*GetDeployedPackageResponse, error)
	// ListDeployedPackages lists all deployed packages
	ListDeployedPackages(ctx context.Context, in *ListDeployedPackagesRequest, opts ...grpc.CallOption) (*ListDeployedPackagesResponse, error)
	// GetPackageMetadata fetches metadata without deploying
	GetPackageMetadata(ctx context.Context, in *GetPackageMetadataRequest, opts ...grpc.CallOption) (*GetPackageMetadataResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type zarfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZarfServiceClient(cc grpc.ClientConnInterface) ZarfServiceClient {
	return &zarfServiceClient{cc}
}

func (c *zarfServiceClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, ZarfService_Deploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zarfServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, ZarfService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zarfServiceClient) GetDeployedPackage(ctx context.Context, in *GetDeployedPackageRequest, opts ...grpc.CallOption) (*GetDeployedPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeployedPackageResponse)
	err := c.cc.Invoke(ctx, ZarfService_GetDeployedPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zarfServiceClient) ListDeployedPackages(ctx context.Context, in *ListDeployedPackagesRequest, opts ...grpc.CallOption) (*ListDeployedPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeployedPackagesResponse)
	err := c.cc.Invoke(ctx, ZarfService_ListDeployedPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zarfServiceClient) GetPackageMetadata(ctx context.Context, in *GetPackageMetadataRequest, opts ...grpc.CallOption) (*GetPackageMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPackageMetadataResponse)
	err := c.cc.Invoke(ctx, ZarfService_GetPackageMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zarfServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ZarfService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZarfServiceServer is the server API for ZarfService service.
// All implementations must embed UnimplementedZarfServiceServer
// for forward compatibility.
type ZarfServiceServer interface {
	// Deploy deploys a Zarf package
	Deploy(context.Context, *DeployRequest) (*DeployResponse, error)
	// Remove removes a deployed package
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	// GetDeployedPackage gets info about a deployed package
	GetDeployedPackage(context.Context, *GetDeployedPackageRequest) (*GetDeployedPackageResponse, error)
	// ListDeployedPackages lists all deployed packages
	ListDeployedPackages(context.Context, *ListDeployedPackagesRequest) (*ListDeployedPackagesResponse, error)
	// GetPackageMetadata fetches metadata without deploying
	GetPackageMetadata(context.Context, *GetPackageMetadataRequest) (*GetPackageMetadataResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedZarfServiceServer()
}

// UnimplementedZarfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZarfServiceServer struct{}

func (UnimplementedZarfServiceServer) Deploy(context.Context, *DeployRequest) (*DeployResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedZarfServiceServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedZarfServiceServer) GetDeployedPackage(context.Context, *GetDeployedPackageRequest) (*GetDeployedPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeployedPackage not implemented")
}
func (UnimplementedZarfServiceServer) ListDeployedPackages(context.Context, *ListDeployedPackagesRequest) (*ListDeployedPackagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeployedPackages not implemented")
}
func (UnimplementedZarfServiceServer) GetPackageMetadata(context.Context, *GetPackageMetadataRequest) (*GetPackageMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPackageMetadata not implemented")
}
func (UnimplementedZarfServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedZarfServiceServer) mustEmbedUnimplementedZarfServiceServer() {}
func (UnimplementedZarfServiceServer) testEmbeddedByValue()                     {}

// UnsafeZarfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZarfServiceServer will
// result in compilation errors.
type UnsafeZarfServiceServer interface {
	mustEmbedUnimplementedZarfServiceServer()
}

func RegisterZarfServiceServer(s grpc.ServiceRegistrar, srv ZarfServiceServer) {
	// If the following call panics, it indicates UnimplementedZarfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZarfService_ServiceDesc, srv)
}

func _ZarfService_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZarfServiceServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZarfService_Deploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZarfServiceServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZarfService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZarfServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZarfService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZarfServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZarfService_GetDeployedPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeployedPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZarfServiceServer).GetDeployedPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZarfService_GetDeployedPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZarfServiceServer).GetDeployedPackage(ctx, req.(*GetDeployedPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZarfService_ListDeployedPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeployedPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZarfServiceServer).ListDeployedPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZarfService_ListDeployedPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZarfServiceServer).ListDeployedPackages(ctx, req.(*ListDeployedPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZarfService_GetPackageMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackageMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZarfServiceServer).GetPackageMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZarfService_GetPackageMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZarfServiceServer).GetPackageMetadata(ctx, req.(*GetPackageMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZarfService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZarfServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZarfService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZarfServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZarfService_ServiceDesc is the grpc.ServiceDesc for ZarfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZarfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zarf.v1.ZarfService",
	HandlerType: (*ZarfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _ZarfService_Deploy_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _ZarfService_Remove_Handler,
		},
		{
			MethodName: "GetDeployedPackage",
			Handler:    _ZarfService_GetDeployedPackage_Handler,
		},
		{
			MethodName: "ListDeployedPackages",
			Handler:    _ZarfService_ListDeployedPackages_Handler,
		},
		{
			MethodName: "GetPackageMetadata",
			Handler:    _ZarfService_GetPackageMetadata_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ZarfService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zarf/v1/zarf.proto",
}
